apiVersion: v1
kind: Service
metadata:
  name: sprocket-v3-api
  namespace: sprocket-v3
spec:
  selector:
    app: sprocket-v3-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      name: http
  type: ClusterIP

