apiVersion: v1
kind: Service
metadata:
  name: kinetic-v3-api
  namespace: kinetic-v3
spec:
  selector:
    app: kinetic-v3-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      name: http
  type: ClusterIP

