package hierarchy

import "context"

type Store interface {
	CreateLeague(ctx context.Context, input CreateLeagueInput) (League, error)
	ListLeagues(ctx context.Context) ([]League, error)
	CreateFranchise(ctx context.Context, input CreateFranchiseInput) (Franchise, error)
	ListFranchises(ctx context.Context) ([]Franchise, error)
	CreateClub(ctx context.Context, input CreateClubInput) (Club, error)
	ListClubs(ctx context.Context) ([]Club, error)
	CreateTeam(ctx context.Context, input CreateTeamInput) (Team, error)
	ListTeams(ctx context.Context) ([]Team, error)
	CreatePlayer(ctx context.Context, input CreatePlayerInput) (Player, error)
	ListPlayers(ctx context.Context) ([]Player, error)
	CreateRosterMembership(ctx context.Context, input CreateRosterMembershipInput) (RosterMembership, error)
	ListRosterMemberships(ctx context.Context) ([]RosterMembership, error)
	CreateQueue(ctx context.Context, input CreateQueueInput) (Queue, error)
	ListQueues(ctx context.Context) ([]Queue, error)
	EnqueueTeam(ctx context.Context, input EnqueueTeamInput) (QueueEntry, error)
	LeaveQueue(ctx context.Context, input LeaveQueueInput) (QueueEntry, error)
	AdvanceQueueEntryStage(ctx context.Context, input AdvanceQueueEntryStageInput) (QueueEntry, error)
	ListActiveQueueEntries(ctx context.Context) ([]QueueEntry, error)
	CreateScrim(ctx context.Context, input CreateScrimInput) (Scrim, error)
	UpdateScrimState(ctx context.Context, input UpdateScrimStateInput) (Scrim, error)
	ListScrims(ctx context.Context) ([]Scrim, error)
	PromoteQueueToScrim(ctx context.Context, input PromoteQueueToScrimInput) (Scrim, error)
	ProcessQueuePromotions(ctx context.Context, input ProcessQueuePromotionsInput) (ProcessQueuePromotionsResult, error)
	ListPromotionProcessingRuns(ctx context.Context) ([]PromotionProcessingRun, error)
	ListPlayerRatings(ctx context.Context) ([]PlayerRating, error)
	ListMatchmakingDecisions(ctx context.Context) ([]MatchmakingDecision, error)
	CreateResultSubmission(ctx context.Context, input CreateResultSubmissionInput) (ResultSubmission, error)
	ListResultSubmissions(ctx context.Context) ([]ResultSubmission, error)
	RatifyResultSubmission(ctx context.Context, input RatifyResultSubmissionInput) (ResultSubmission, error)
	RejectResultSubmission(ctx context.Context, input RejectResultSubmissionInput) (ResultSubmission, error)
	IngestReplayEvidence(ctx context.Context, input IngestReplayEvidenceInput) (ReplayIngestionResult, error)
	ListReplayEvidence(ctx context.Context) ([]ReplayEvidence, error)
	ListReplayParseRuns(ctx context.Context) ([]ReplayParseRun, error)
	ListResultSubmissionReplayLinks(ctx context.Context) ([]ResultSubmissionReplayLink, error)
	CreateSeason(ctx context.Context, input CreateSeasonInput) (Season, error)
	ListSeasons(ctx context.Context) ([]Season, error)
	CreateScheduleGroup(ctx context.Context, input CreateScheduleGroupInput) (ScheduleGroup, error)
	ListScheduleGroups(ctx context.Context) ([]ScheduleGroup, error)
	CreateFixture(ctx context.Context, input CreateFixtureInput) (Fixture, error)
	ListFixtures(ctx context.Context) ([]Fixture, error)
	CreateMatch(ctx context.Context, input CreateMatchInput) (Match, error)
	ListMatches(ctx context.Context) ([]Match, error)
}
